@extends('layouts.userview')

@section('pagename', 'Política de privacidad')

@section('content')

<div class="container">
    <h1 class="title text-center mt-5 titulo-pagina">Política de privacidad</h1>
    <p style="font-size: 17px;margin-bottom: 22px;">
        TALLER EMPRESARIAL 2.0, SL, con CIF: B-56.096.332. (en delante, la “EMPRESA”), domicilio en Manuel Fuentes Bocanegra, 15- 4º4 14005, Córdoba, teléfono.: 675045062, y email.: info@tallerempresarial.es es el titular del sitio web gestioninstalacion.es (en adelante el “Sitio Web”) y el responsable del tratamiento de los datos personales que el usuario facilite al acceder o utilizar el sitio web y de todos los datos personales en general que se recogen en el mismo o gestiona la Empresa. 
        La Empresa, informa, través de esta Política de Privacidad, sobre el tratamiento y protección de los datos de carácter personal de los usuarios que puedan ser recabados mediante su navegación o contratación de servicios que realice en este portal o por otras vías con la Empresa. 
        El uso de esta web por parte del usuario conlleva la aceptación por su parte de esta Política de Privacidad. La Empresa adopta las medidas necesarias para garantizar la seguridad, integridad y confidencialidad de los datos conforme a lo establecido en el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de Abril de 2016, 
        relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de los mismos, y en aquello no previsto por éste por la Ley Orgánica 3/2018, de 5 de Diciembre, de Protección de Datos Personales y Garantía de los Derechos Digitales y la Ley 34/2002, de 11 de Julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico. 
    </p>
    <p style="font-size: 17px;margin-bottom: 22px;">Finalidad:</p>
    <p style="font-size: 17px;margin-bottom: 22px;">Los datos son recabados con las siguientes finalidades:</p>
    <p style="font-size: 17px;margin-bottom: 22px;"><strong> Asegurar la correcta gestión de los servicios: </strong></p>
    <p style="font-size: 17px;margin-bottom: 22px; margin-left:15px">- Gestión de reservas online  </p>
    <p style="font-size: 17px;margin-bottom: 22px; margin-left:15px">- Proporcionarle información relacionada con los productos y servicios que ofrece nuestra empresa y que se detallan en este sitio web. </p>
    <p style="font-size: 17px;margin-bottom: 22px; margin-left:15px">- Vigilancia del uso del sitio web, con el objetivo de evitar y detectar actuaciones fraudulentas en ésta, así como cualquier acceso no autorizado.  </p>
    <p style="font-size: 17px;margin-bottom: 22px;"><strong> Atención a los derechos de las personas:  </strong></p>
    <p style="font-size: 17px;margin-bottom: 22px; margin-left:15px">- Atender las solicitudes de los interesados en el ejercicio de los derechos que establece el Reglamento General de Protección de Datos.</p>
    <p style="font-size: 17px;margin-bottom: 22px;">La finalidad del tratamiento en ningún caso tiene por objeto la elaboración de perfiles para la personalización de publicidad propia o de terceros o el análisis del tráfico en nuestra web. No tomamos decisiones automatizadas en base a perfiles, a excepción de la personalización de publicidad y la prevención del fraude en internet. Le informamos que podrá revocar el consentimiento, en cada comunicado comercial o publicitario que se le haga llegar, y en cualquier momento, mediante la notificación al domicilio de la Empresa, arriba reseñado, o a través de correo electrónico a info@tallerempresarial.es.</p>
    <p style="font-size: 17px;margin-bottom: 22px;"><strong>Base Jurídica y plazo de conservación:</strong> El tratamiento de los datos personales que proporciona el usuario se realiza amparado en las siguientes bases jurídicas que legitiman el mismo:</p>
    <p style="font-size: 17px;margin-bottom: 22px; margin-left:15px">-  El consentimiento libre, específico, informado e inequívoco, En caso de que el interesado no facilite los datos o éstos sean erróneos o inexactos, no podremos atender su solicitud, resultando imposible proporcionarle la información solicitad. Los datos serán conservados mientras no nos solicite su baja. Como ya hemos informado anteriormente tendrá derecho a retirar su consentimiento en cualquier momento, sin que ello afecte a la licitud del tratamiento basado en el consentimiento previo a su retirada. Los datos se conservarán durante los plazos legalmente exigidos.</p>
    <p style="font-size: 17px;margin-bottom: 22px;"><strong>Destinatarios:</strong> El tratamiento de los datos personales que proporciona el usuario se realiza amparado en las siguientes bases jurídicas que legitiman el mismo: Con carácter general la Empresa no comunicará estos datos personales a terceros, excepto al Administrador de la Comunidad de propietarios donde se presta el servicio si así lo requiere y a terceros en caso de que la prestación de un servicio implique la necesidad de una relación contractual con un encargado de tratamiento y ello sea estrictamente necesario para gestionar y mantener la relación entre el usuario y la mencionada empresa, previa autorización expresa por parte del usuario. Esto se hará sólo durante el tiempo imprescindible para posibilitar la ejecución del contrato de encargo, y en las mismas condiciones y con las misma responsabilidad que se le exigen al responsable. Una vez finalizado el encargo, el encargado del tratamiento devolverá al Responsable los datos personales y suprimirá cualquier copia de la que disponga. Por otra parte, sólo tendrán derecho a acceder a estos datos personales los terceros con los que la Empresa tenga una obligación legal o contractual de facilitarlos, entre los que se incluyen, por ejemplo, los Jueces y Tribunales interesados en los procedimientos relacionados con las reclamaciones presentadas. No están previstas las <strong>transferencias internacionales de datos.</strong></p>
    <p style="font-size: 17px;margin-bottom: 22px;"><strong>Derechos de los interesados:</strong>  El usuario podrá ejercitar en todo momento, en los términos establecidos en la legislación vigente, los derechos de acceso, rectificación o supresión de datos, solicitar que se limite el tratamiento, oponerse al mismo, solicitar la portabilidad de sus datos, así como revocar el consentimiento prestado, derechos reconocidos en el citado Reglamento (UE). El ejercicio de estos derechos puede realizarlo el propio usuario dirigiéndose a la Empresa en la dirección de su sede social indicada anteriormente o a través del envío de un correo electrónico a la dirección de correo info@tallerempresarial.es. Para el efectivo ejercicio de estos derechos, el usuario deberá acreditar su identidad facilitando su nombre y apellidos, fotocopia del DNI o documento identificativo equivalente que acredite su identidad, petición en la que se concrete la solicitud, la dirección a efectos de notificaciones, y fecha y firma del solicitante. Asimismo, el usuario podrá reclamar ante la <a href="https://www.aepd.es/es">Agencia Española de Protección de Datos (AEPD)</a>, especialmente cuando no haya obtenido satisfacción en el ejercicio de sus derechos, mediante escrito dirigido a la misma, a Manuel Fuentes Bocanegra 15- 4º4 14005, Córdoba. </p>

</div>

@endsection